apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-angular-app
  template:
    metadata:
      labels:
        app: springboot-angular-app
    spec:
      containers:
        - name: springboot-angular-app
          image: prashant302/myproject:v1.0	
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_DRIVER
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-angular-service
spec:
  selector:
    app: springboot-angular-app
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer
